config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "sessions#new"
  get 'home', to: "materials#index"
  resources :posts do
    member do
      post 'vote'
    end
  end
  resources :categories
  resources :comments do
    member do
      post 'vote'
    end
  end
  resources :sessions
  resources :users
  resources :portfolios
  resources :assignments do
    resources :letters do
      member do
        post 'vote'
      end
    end
  end
  resources :materials
  get 'register', to: "users#new"
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  get 'search', to: 'search#index'
  get 'posts/:id/newcomment', to: 'posts#newcomment'
  post '/login', to: 'sessions#create'
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :letters
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def index
    @assignments = Assignment.all.sort_by{|x| x.created_at}.reverse
  end

  def show
    @assignment = Assignment.find(params[:id])
    @letters = @assignment.letters.order(created_at: :desc)
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      flash[:notice] = "The assignment was created."
      redirect_to assignments_path
    else
      flash[:danger] = "There was an error."
      render :new
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    if @assignment.update(assignment_params)
      flash[:notice] = "The assignment was updated."
      redirect_to assignments_path(@assignment)
    else
      render :edit
    end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to assignments_path
  end

private

  def assignment_params
    params.require(:assignment).permit!
  end

  def set_assignment
    @assignment = Assignment.find(params[:id])
  end
end

app/views/assignments/edit.html.erb
<script type='text/javascript' charset='UTF-8'>
  $(document).ready(function(){
    $('form[data-remote]').bind('ajax:before', function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <%= form_for @assignment do |f| %>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :title %>
            </br>
            <%= f.text_field :title, class: "col-md-8" %>
          </div>
        </div>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :body %>
            </br>
            <%= f.cktext_area :body, rows: 12, class: "col-md-8" %>
          </div>
        </div>
        </br>
        <div class='row'>
          <div class='control-group'>
            <%= f.submit(@assignment.new_record? ? 'Create Assignment' : 'Update Assignment', class: 'btn btn-primary')%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/assignments/index.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class='jumbotron'>
    <div class="row">
      <h3>Assignments</h3>
      <% if logged_in? and current_user.admin? %>
        <div><%= link_to "Create New Assignment", new_assignment_path, class: "btn btn-lg btn-primary" %></div>
      <% end %>
    </div>
    <ul>
    <% @assignments.each do |assignment| %>
      <li>
        <h4><%= link_to("#{assignment.title}", assignment_path(assignment))%></h4>
      </li>
    <% end %>
  </div>
</div>

app/views/assignments/new.html.erb
<script type='text/javascript' charset='UTF-8'>
  $(document).ready(function(){
    $('form[data-remote]').bind('ajax:before', function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <%= form_for @assignment do |f| %>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :title %>
            </br>
            <%= f.text_field :title, class: "col-md-8" %>
          </div>
        </div>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :body %>
            </br>
            <%= f.cktext_area :body, rows: 12, class: "col-md-8" %>
          </div>
        </div>
        </br>
        <div class='row'>
          <div class='control-group'>
            <%= f.submit(@assignment.new_record? ? 'Create Assignment' : 'Update Assignment', class: 'btn btn-primary')%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/assignments/show.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h3><%= @assignment.title %></h3>
      <p><%= @assignment.body.html_safe %></p>
      <% if logged_in? and current_user.admin? %>
        <div class="row">  
          <div><%= link_to "Edit this assignment",edit_assignment_path(@assignment), class: "btn btn-sm btn-success" %></div>
        </div>
      <% end %>
      <% if logged_in? and current_user.admin? %>
        </br>
        <div class="row">  
          <div><%= link_to "Delete this assignment", @assignment, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %></div>
        </div>
        </br>
      <% end %>
      <% if logged_in? and current_user.user_name != 'Guest' %>
        <div class="row">  
          <p>
            <%= link_to "Create New Letter", new_assignment_letter_path(@assignment, @letter), class: "btn btn-lg btn-primary" %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
  <% @letters.each do |letter| %>
    <%= render 'letters/letter', letter: letter %>
  <% end %>