config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "sessions#new"
  get 'home', to: "materials#index"
  resources :posts do
    member do
      post 'vote'
    end
  end
  resources :categories
  resources :comments do
    member do
      post 'vote'
    end
  end
  resources :sessions
  resources :users
  resources :portfolios
  resources :assignments do
    resources :letters do
      member do
        post 'vote'
      end
    end
  end
  resources :materials
  get 'register', to: "users#new"
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  get 'search', to: 'search#index'
  get 'posts/:id/newcomment', to: 'posts#newcomment'
  post '/login', to: 'sessions#create'
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
end

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= is_active?(posts_path) %>"><%= link_to "Forum", posts_path %></li>
        <li class="<%= is_active?(assignments_path) %>"><%= link_to "Letters", assignments_path %></li>
        <li class="<%= is_active?(portfolios_path) %>"><%= link_to "Portfolios", portfolios_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/portfolios/<%= current_user.id %>"><%= current_user.user_name %></a></li>
        <li class="divider"></li>
        <li><a href="/sign_out">Sign Out</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "alert alert-info", :id => "flash_#{name}" %>
  <% end %>
<% end %>