config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "sessions#new"
  get 'home', to: "materials#index"
  resources :posts do
    member do
      post 'vote'
    end
  end
  resources :categories
  resources :comments do
    member do
      post 'vote'
    end
  end
  resources :sessions
  resources :users
  resources :portfolios
  resources :assignments do
    resources :letters do
      member do
        post 'vote'
      end
    end
  end
  resources :materials
  get 'register', to: "users#new"
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  get 'search', to: 'search#index'
  get 'posts/:id/newcomment', to: 'posts#newcomment'
  post '/login', to: 'sessions#create'
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
end

app/models/letter.rb
class Letter < ActiveRecord::Base
  include Voteable

  has_many :comments, as: :commentable
  belongs_to :assignment
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_assignment_and_letter, only: [:edit, :update, :destroy]
  before_action :require_user
  before_action :require_creator, only: [:edit, :update]

  def index
    @assignment = Assignment.find(params[:assignment_id])
    @letters = @assignment.letters.order(created_at: :desc)
  end

  def show
    @assignment = Assignment.find(params[:assignment_id])
    @letter = @assignment.letters.find(params[:id])
    @comments = @letter.comments
    @comment = Comment.new
  end

  def new
    @assignment = Assignment.find(params[:assignment_id])
    @letter = @assignment.letters.new
  end

  def create
    @assignment = Assignment.find(params[:assignment_id])
    @letter = @assignment.letters.new(letter_params)
    @letter.creator = current_user
    if @letter.save
      flash[:notice] = "Your letter was created."
      redirect_to assignment_path(@assignment)
    else
      flash[:danger] = "There was an error."
      render :new
    end
  end

  def edit
  end

  def update
    if @letter.update(letter_params)
      flash[:notice] = "The letter was updated."
      redirect_to assignment_letter_path(@assignment, @letter)
    else
      render :edit
    end
  end

  def destroy
    @letter.destroy
    redirect_to assignments_path
  end

  def search
    @results = Letter.search_by_title(params[:search_term])
  end

  def vote
    @assignment = Assignment.find(params[:assignment_id])
    @letter = @assignment.letters.find(params[:id])
    @vote = Vote.create(voteable: @letter, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if !@vote.valid?
          flash[:error] = 'You can only favorite a letter once.'
        end
      redirect_to :back
      end
      format.js
      end
  end


private

  def set_assignment_and_letter
    @assignment = Assignment.find(params[:assignment_id])
    @letter = @assignment.letters.find(params[:id])
  end

  def letter_params
    params.require(:letter).permit!
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @letter.creator || current_user.admin?)
  end

end

app/views/letters/_letter.html.erb
<div class="row">
  <div class="jumbotron">
    <h3><%= link_to("#{letter.title}", assignment_letter_path(letter.assignment_id, letter))%></h3>
    <p><%= letter.body.html_safe %> </p>
    <p>
      <small>Posted by <%= letter.creator.user_name %>, <%= display_datetime(letter.created_at) %></small>
    </p>
    <small>
      <span>
        <% if logged_in? and current_user.user_name != 'Guest' %>
          <%= link_to vote_assignment_letter_path(letter.assignment_id, letter, vote: true), method: 'post' do%>
            <% if Vote.where("voteable_type = 'Letter' AND voteable_id = ? AND user_id = ?", letter.id, current_user.id) != [] %>
              <i class="glyphicon glyphicon-heart"></i>
            <% else %>
              <i class="glyphicon glyphicon-heart-empty"></i>
            <% end %>
          <% end %>
        <% end %>
        <% if current_user.user_name == 'Guest' %>
          <i class="glyphicon glyphicon-heart"></i>
        <% end %>
        <span id='letter_<%=letter.id%>_votes'><%= letter.total_votes %></span>
        <%= link_to("Comments: #{letter.comments.length}", assignment_letter_path(letter.assignment_id, letter)) %>
        <br/>
      </span>
    </small>
  </div>
</div>

app/views/letters/edit.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <%= form_for @letter do |f| %>
      <div class='row'>
        <div class='control-group'>
          <%= f.label :title %>
          </br>
          <%= f.text_field :title, class: "col-md-8" %>
        </div>
      </div>
      <div class='row'>
        <div class='control-group'>
          <%= f.label :body %>
          </br>
          <%= f.cktext_area :body, rows: 12, class: "col-md-8" %>
        </div>
      </div>
      </br>
      <div class='row'>
        <div class='control-group'>
          <%= f.submit(@letter.new_record? ? 'Create letter' : 'Update letter', class: 'btn btn-primary')%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/letters/index.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="well">
      <h1>Letters</h1>
    </div>
  </div>
  <div class="row">  
    <p>
      <a class="btn btn-lg btn-primary" href="../../letters/new" role="button">Create New Letter &raquo;
      </a>
    </p>
  </div>
  <% @letters.each do |letter| %>
    <%= render 'letter', letter: letter %>
  <% end %>
</div>

app/views/letters/new.html.erb
<script type='text/javascript' charset='UTF-8'>
  $(document).ready(function(){
    $('form[data-remote]').bind('ajax:before', function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <%= form_for [@letter.assignment, @letter] do |f| %>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :title %>
            </br>
            <%= f.text_field :title, class: "col-md-8" %>
          </div>
        </div>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :body %>
            </br>
            <%= f.cktext_area :body, rows: 12, class: "col-md-8" %>
          </div>
        </div>
        </br>
        <div class='row'>
          <div class='control-group'>
            <%= f.submit(@letter.new_record? ? 'Create letter' : 'Update letter', class: 'btn btn-primary')%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/letters/show.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h3><%= @letter.title %></h3>
      <p><%= @letter.body.html_safe %> </p>
      <p>
        <small>Posted by <%= @letter.creator.user_name %>, <%= display_datetime(@letter.created_at) %></small>
      </p>
      <% if logged_in? and (current_user == @letter.creator || current_user.admin?) %>
        <div><%= link_to "Edit this letter",edit_assignment_letter_path(@assignment, @letter), class: "btn btn-sm btn-success" %></div>
      <% end %>
      <% if logged_in? and (current_user == @letter.creator || current_user.admin?) %>
        </br>
        <div><%= link_to "Delete this letter", assignment_letter_path(@assignment, @letter), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %></div>
      <% end %>
      <span>
        <% if logged_in? and current_user.user_name != 'Guest' %>
          <%= link_to vote_assignment_letter_path(@letter.assignment_id, @letter, vote: true), method: 'post' do%>
            <% if Vote.where("voteable_type = 'Letter' AND voteable_id = ? AND user_id = ?", @letter.id, current_user.id) != [] %>
              <i class="glyphicon glyphicon-heart"></i>
            <% else %>
              <i class="glyphicon glyphicon-heart-empty"></i>
            <% end %>
          <% end %>
        <% end %>
        <% if current_user.user_name == 'Guest' %>
          <i class="glyphicon glyphicon-heart"></i>
        <% end %>
        <span id='letter_<%=@letter.id%>_votes'><%= @letter.total_votes %></span>
        <%= link_to("Comments: #{@letter.comments.length}", assignment_letter_path(@letter.assignment_id, @letter)) %>
        <br/>
      </span>
    </div>
  </div>
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
    <% if logged_in? and current_user.user_name != 'Guest' %>
      <div class='row'>
        <div class="col-sm-11 col-sm-offset-1">
          <div class="well">
            <h3>Add a comment:</h3>
            <%= form_for @comment, :url => comments_path(:commentable_type => "letter", :commentable_id => @letter.id) do |f| %>
              <div class="control-group">
                <%= f.text_area :body, rows: 5, class: "col-sm-11" %>
              </div>
              <div class="row">
                <div class="col-sm-11">
                  </br>
                  <%= f.submit "Post comment", class: 'btn btn-primary' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>