config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "sessions#new"
  get 'home', to: "materials#index"
  resources :posts do
    member do
      post 'vote'
    end
  end
  resources :categories
  resources :comments do
    member do
      post 'vote'
    end
  end
  resources :sessions
  resources :users
  resources :portfolios
  resources :assignments do
    resources :letters do
      member do
        post 'vote'
      end
    end
  end
  resources :materials
  get 'register', to: "users#new"
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  get 'search', to: 'search#index'
  get 'posts/:id/newcomment', to: 'posts#newcomment'
  post '/login', to: 'sessions#create'
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable

  has_many :comments, as: :commentable

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :require_creator, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 20).order('created_at DESC')
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      flash[:notice] = "There was an error."
      render :new
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def update

    if @post.update(post_params)
      flash[:notice] = "The post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def search
    @results = Post.search_by_title(params[:search_term])
  end

  def vote
    @post = Post.find(params[:id])
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if !@vote.valid?
          flash[:error] = 'You can only favorite a post once.'
        end
      redirect_to :back
      end
      format.js
      end
  end


private

  def post_params
    params.require(:post).permit(:title, :body, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def render_posts(posts)
    if posts.to_a.size > 0
      render(posts)
    else
      content_tag(:div, "No posts were found", class: 'message')
    end
  end
end

app/views/posts/_post.html.erb
<div class="row">
  <div class="jumbotron">
    <h3><%= link_to("#{post.title}", post_path(post))%></h3>
    <p><%= post.body.truncate(570).html_safe %> </p>
    <p>
      <small>Posted by <%= post.creator.user_name %>, <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
    <span>
      <% if logged_in? and current_user.user_name != 'Guest' %>
        <%= link_to vote_post_path(post, vote: true), method: 'post' do%>
          <% if Vote.where("voteable_type = 'Post' AND voteable_id = ? AND user_id = ?", post.id, current_user.id) != [] %>
            <i class="glyphicon glyphicon-heart"></i>
          <% else %>
            <i class="glyphicon glyphicon-heart-empty"></i>
          <% end %>
        <% end %>
      <% end %>
      <% if current_user.user_name == 'Guest' %>
        <i class="glyphicon glyphicon-heart"></i>
      <% end %>
      <span id='post_<%=post.id%>_votes'><%= post.total_votes %></span>
      <%= link_to("Comments: #{post.comments.length}", post_path(post)) %>
      <br/>
    </span>
  </small>
  </div>
</div>

app/views/posts/edit.html.erb
<script type='text/javascript' charset='UTF-8'>
  $(document).ready(function(){
    $('form[data-remote]').bind('ajax:before', function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <%= form_for @post do |f| %>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :title %>
            </br>
            <%= f.text_field :title, class: "col-md-8" %>
          </div>
        </div>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :body %>
            </br>
            <%= f.cktext_area :body, rows: 12, class: "col-md-8" %>
          </div>
        </div>
        </br>
        <div class='row'>
          <div class='control-group'>
            <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary')%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'shared/header' %>
<div class="container">
  <% if logged_in? and current_user.user_name != 'Guest' %>
    <div class="row">     
      <p>
        <a class="btn btn-lg btn-primary" href="../../posts/new" role="button">Create New Post &raquo;
        </a>
      </p>
    </div>
  <% end %>
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
  <div class="row">
    <div class="my_pagination">
      <%= will_paginate @posts, :order => 'created_at DESC' %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<script type='text/javascript' charset='UTF-8'>
  $(document).ready(function(){
    $('form[data-remote]').bind('ajax:before', function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <%= form_for @post do |f| %>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :title %>
            </br>
            <%= f.text_field :title, class: "col-md-8" %>
          </div>
        </div>
        <div class='row'>
          <div class='control-group'>
            <%= f.label :body %>
            </br>
            <%= f.cktext_area :body, rows: 12, class: "col-md-8" %>
          </div>
        </div>
        </br>
        <div class='row'>
          <div class='control-group'>
            <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary')%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="row">
    <div class="jumbotron">
      <h3><%= @post.title %></h3>
      <p><%= @post.body.html_safe %> </p>
      <p>
        <small>Posted by <%= @post.creator.user_name %>, <%= display_datetime(@post.created_at) %></small>
      </p>
      <% if logged_in? and (current_user == @post.creator || current_user.admin?) %>
        <div><%= link_to "Edit this post",edit_post_path(@post), class: "btn btn-sm btn-success" %></div>
      <% end %>
      <% if logged_in? and (current_user == @post.creator || current_user.admin?) %>
        </br>
        <div><%= link_to "Delete this post", @post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %></div>
      <% end %>
    <% if logged_in? and current_user.user_name != 'Guest' %>
      <%= link_to vote_post_path(@post, vote: true), method: 'post' do%>
        <% if Vote.where("voteable_type = 'Post' AND voteable_id = ? AND user_id = ?", @post.id, current_user.id) != [] %>
          <i class="glyphicon glyphicon-heart"></i>
        <% else %>
          <i class="glyphicon glyphicon-heart-empty"></i>
        <% end %>
      <% end %>
    <% end %>
    <% if current_user.user_name == 'Guest' %>
      <i class="glyphicon glyphicon-heart"></i>
    <% end %>
    <span id='post_<%=@post.id%>_votes'><%= @post.total_votes %></span>
    <br/>
  </div>
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
    <% if logged_in? and current_user.user_name != 'Guest' %>
      <div class='row'>
        <div class="col-sm-11 col-sm-offset-1">
          <div class="well">
            <h3>Add a comment:</h3>
            <%= form_for @comment, :url => comments_path(:commentable_type => "post", :commentable_id => @post.id) do |f| %>
              <div class="control-group">
                <%= f.text_area :body, rows: 5, class: "col-sm-11" %>
              </div>
              <div class="row">
                <div class="col-sm-11">
                  </br>
                  <%= f.submit "Post comment", class: 'btn btn-primary' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>